name: Promote member to team maintainer
description: Promote GitHub member to team maintainer
branding:
  icon: 'corner-right-up'
  color: 'orange'
inputs:
  user:
    description: 'GitHub User Name'
    required: true
  team:
    description: 'GitHub Team Name'
    required: true
  org:
    description: 'GitHub Organization Name'
    required: true
  github_token:
    description: 'GitHub personal access token for the organization owner with admin:org scope'
    required: true
runs:
  using: composite
  steps:
    - run: bash ${{ github.action_path }}/main.sh ${{ inputs.user}} ${{ inputs.team }} ${{ inputs.org }
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
